config/routes.rb
Rails.application.routes.draw do
  resources :dexes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dex.rb
class Dex < ActiveRecord::Base
    has_attached_file :image, styles: { medium: '200x200>', thumb: '48x48>' }
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dexes_controller.rb
class DexesController < ApplicationController
  before_action :set_dex, only: [:show, :edit, :update, :destroy]

  # GET /dexes
  # GET /dexes.json
  def index
    @dexes = Dex.all
  end

  # GET /dexes/1
  # GET /dexes/1.json
  def show
  end

  # GET /dexes/new
  def new
    @dex = Dex.new
  end

  # GET /dexes/1/edit
  def edit
  end

  # POST /dexes
  # POST /dexes.json
  def create
    @dex = Dex.new(dex_params)

    respond_to do |format|
      if @dex.save
        format.html { redirect_to @dex, notice: 'Dex was successfully created.' }
        format.json { render :show, status: :created, location: @dex }
      else
        format.html { render :new }
        format.json { render json: @dex.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dexes/1
  # PATCH/PUT /dexes/1.json
  def update
    respond_to do |format|
      if @dex.update(dex_params)
        format.html { redirect_to @dex, notice: 'Dex was successfully updated.' }
        format.json { render :show, status: :ok, location: @dex }
      else
        format.html { render :edit }
        format.json { render json: @dex.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dexes/1
  # DELETE /dexes/1.json
  def destroy
    @dex.destroy
    respond_to do |format|
      format.html { redirect_to dexes_url, notice: 'Dex was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dex
      @dex = Dex.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dex_params
      params.require(:dex).permit(:name, :descripcion, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dexes_helper.rb
module DexesHelper
end

app/views/dexes/_form.html.erb
<%= form_with(model: dex, local: true) do |form| %>
  <% if dex.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dex.errors.count, "error") %> prohibited this dex from being saved:</h2>

      <ul>
      <% dex.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :dex_name %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion, id: :dex_descripcion %>
  </div>
   <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :dex_image %>
  </div>
 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dexes/edit.html.erb
<h1>Editing Dex</h1>

<%= render 'form', dex: @dex %>

<%= link_to 'Show', @dex %> |
<%= link_to 'Back', dexes_path %>

app/views/dexes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>POKEDEX</h1>


<table>
  <thead>
    <tr>
      <th>Pokemon</th>
      
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @dexes.each do |dex| %>
      <tr>
        <td><%= image_tag dex.image.url(:thumb) %></td>
        <td><%= dex.name %></td>
        <td><%= dex.descripcion %></td>
        <td><%= link_to 'Show', dex %></td>
        <td><%= link_to 'Edit', edit_dex_path(dex) %></td>
        <td><%= link_to 'Destroy', dex, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Dex', new_dex_path %>

app/views/dexes/new.html.erb
<h1>New Dex</h1>

<%= render 'form', dex: @dex %>

<%= link_to 'Back', dexes_path %>

app/views/dexes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dex.name %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @dex.descripcion %>
</p>

<%= image_tag @dex.image.url(:medium) %>


<%= link_to 'Edit', edit_dex_path(@dex) %> |
<%= link_to 'Back', dexes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>